/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsKairoRouteImport } from './routes/projects/kairo'
import { Route as ProjectsCanvazzFlowRouteImport } from './routes/projects/canvazz-flow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsKairoRoute = ProjectsKairoRouteImport.update({
  id: '/projects/kairo',
  path: '/projects/kairo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCanvazzFlowRoute = ProjectsCanvazzFlowRouteImport.update({
  id: '/projects/canvazz-flow',
  path: '/projects/canvazz-flow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/canvazz-flow': typeof ProjectsCanvazzFlowRoute
  '/projects/kairo': typeof ProjectsKairoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/canvazz-flow': typeof ProjectsCanvazzFlowRoute
  '/projects/kairo': typeof ProjectsKairoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/canvazz-flow': typeof ProjectsCanvazzFlowRoute
  '/projects/kairo': typeof ProjectsKairoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/canvazz-flow' | '/projects/kairo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/canvazz-flow' | '/projects/kairo'
  id: '__root__' | '/' | '/projects/canvazz-flow' | '/projects/kairo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsCanvazzFlowRoute: typeof ProjectsCanvazzFlowRoute
  ProjectsKairoRoute: typeof ProjectsKairoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kairo': {
      id: '/projects/kairo'
      path: '/projects/kairo'
      fullPath: '/projects/kairo'
      preLoaderRoute: typeof ProjectsKairoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/canvazz-flow': {
      id: '/projects/canvazz-flow'
      path: '/projects/canvazz-flow'
      fullPath: '/projects/canvazz-flow'
      preLoaderRoute: typeof ProjectsCanvazzFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsCanvazzFlowRoute: ProjectsCanvazzFlowRoute,
  ProjectsKairoRoute: ProjectsKairoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
